# config.yaml
# Terminal/Konsole Befehle im Pfad des Repositories ausf체hren:
# f체r neue conda Umgebung: conda env create -f config.yaml
# f체r Update einer bestehende conda Umgebung (wenn zus채tzliche Pakete installiert werden sollen): conda env update -f config.yaml
# Conda Umgebung aktivieren: conda activate intro_ds_ai
# Conda Umgebung deaktivieren: conda deactivate
####################
####################
name: intro_ds_ai
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - missingno
  - statsmodels
  - scipy
  - ipykernel
  - scikit-learn
  - pyarrow
